name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
    - name: Automatic Merge
      uses: lots0logs/gh-action-auto-merge@1.0.0
    - name: action-push
      uses: ludeeus/action-push@0.0.1
      
